//===========================================================================
// vectors.h -- reader for the BCMC test-vector format
//
// The vector files in sim/vectors/ are generated by
// validation/gen_vectors.py from validation/reference.py. This reader has no
// dependencies beyond the C++ standard library so that the same files can be
// consumed by the Verilator harness and, in Verilog, by sim/tb_core.v.
//
// Format (blank lines are insignificant, '#' begins a comment to end of line):
//
//     N 8
//     C 3
//
//     6
//     3
//     5
//
//     ---
//
//     0
//     6
//     1
//
// A case always begins with an `N` line, so no case separator is needed and
// C = 0 requires no special handling.
//===========================================================================

#ifndef BCMC_SIM_VECTORS_H
#define BCMC_SIM_VECTORS_H

#include <cstdint>
#include <string>
#include <vector>

namespace bcmc {

// One test case: the inputs (N, weights) and the offsets that
// validation/reference.py's bcmc_core() produced for them.
struct Case {
    uint32_t              N       = 0;
    uint32_t              C       = 0;
    std::vector<uint32_t> weights;
    std::vector<uint32_t> offsets;
    int                   line    = 0;  // line of the `N` keyword, for messages
};

// Parses `path`. Throws std::runtime_error on any malformed input; a vector
// file that cannot be parsed is a failure, never something to skip over.
std::vector<Case> load_vectors(const std::string& path);

}  // namespace bcmc

#endif  // BCMC_SIM_VECTORS_H
