//===========================================================================
// vectors.h -- reader for the BCMC test-vector formats
//
// The vector files in sim/vectors/ are generated by
// validation/gen_vectors.py from validation/reference.py. This reader has no
// dependencies beyond the C++ standard library so that the same files can be
// consumed by the Verilator harness and, in Verilog, by sim/tb_core.v and
// sim/tb_cell.v.
//
// There are three formats, one per shape of module. All ignore blank lines and
// treat '#' as a comment to end of line.
//
// CORE FORMAT (core_*.txt) -- one streamed transform per case:
//
//     N 8
//     C 3
//
//     6
//     3
//     5
//
//     ---
//
//     0
//     6
//     1
//
// A case always begins with an `N` line, so no case separator is needed and
// C = 0 requires no special handling.
//
// CELL FORMAT (cell_*.txt) -- one evaluation per line, because an exhaustive
// sweep runs to hundreds of thousands of cases:
//
//     #    N  weight  offset  column  bit
//          8       6       0       3    1
//
// MATRIX FORMAT (matrix_*.txt) -- one whole matrix per case, for the two
// projections bcmc_row and bcmc_column:
//
//     N 8 C 3
//     W 6 3 5
//     O 0 6 1
//     R 11111100
//     R 11000001
//     R 01111100
//     L 3 2 2 2 2 2 1 1
//
// The R strings are written column 0 first, matching rtl/bcmc_row.v, where
// row_bits[0] is column 0. L is the column occupancy vector: the quantity the
// Balance Theorem constrains.
//
//===========================================================================

#ifndef BCMC_SIM_VECTORS_H
#define BCMC_SIM_VECTORS_H

#include <cstdint>
#include <string>
#include <vector>

namespace bcmc {

// One test case: the inputs (N, weights) and the offsets that
// validation/reference.py's bcmc_core() produced for them.
struct Case {
    uint32_t              N       = 0;
    uint32_t              C       = 0;
    std::vector<uint32_t> weights;
    std::vector<uint32_t> offsets;
    int                   line    = 0;  // line of the `N` keyword, for messages
};

// One evaluation of the characteristic function: the inputs, and the bit that
// validation/reference.py's bcmc_cell() produced for them.
struct CellCase {
    uint32_t N      = 0;
    uint32_t weight = 0;
    uint32_t offset = 0;
    uint32_t column = 0;
    uint32_t bit    = 0;
    int      line   = 0;  // line the case came from, for messages
};

// One whole matrix, as validation/reference.py's bcmc_matrix() produced it,
// together with the observables the matrix-level theorems talk about.
struct MatrixCase {
    uint32_t                          N = 0;
    uint32_t                          C = 0;
    std::vector<uint32_t>             weights;    // C entries
    std::vector<uint32_t>             offsets;    // C entries, from bcmc_core
    std::vector<std::vector<uint8_t>> rows;       // C rows of N bits, col 0 first
    std::vector<uint32_t>             occupancy;  // N entries, L(j)
    int                               line = 0;   // line of the `N` keyword

    // W = sum of the weights. The Balance Theorem depends on nothing else.
    uint32_t total_weight() const {
        uint32_t w = 0;
        for (uint32_t x : weights) w += x;
        return w;
    }
};

// Parses `path`. Throws std::runtime_error on any malformed input; a vector
// file that cannot be parsed is a failure, never something to skip over.
std::vector<Case>       load_vectors(const std::string& path);
std::vector<CellCase>   load_cell_vectors(const std::string& path);
std::vector<MatrixCase> load_matrix_vectors(const std::string& path);

}  // namespace bcmc

#endif  // BCMC_SIM_VECTORS_H
