"""
Observer hardware test vectors: one run, cycle by cycle.

This is the generator for `sim/vectors/obshw_*.txt`, the files that
`sim/bcmc_observer_hw_test.cpp` and `sim/tb_observer.v` replay against
`rtl/bcmc_observer.v`.

Every expected value in those files is produced by `observer_hw.py`, the golden
engine, which is itself held to `docs/Hardware_Observer_Architecture.md`. The
harnesses therefore compare RTL against a model that was checked against a
document, the same chain the Core, the cell and the peripheral were held to --
never against numbers a testbench made up.

The format
----------

One run is a header and then one line per clock cycle, inputs and expected
outputs together, so a harness replays rather than computes:

    H <N> <oneshot> <cycles>
    C <rst> <start> <trigger> <valid> <state> <running> <column> <scheduled>
      <visit_valid> <done> <aborted>

`state` is 0 for IDLE and 1 for RUN; `running` repeats it as an output, kept
separate so a harness that confuses the two is caught rather than flattered.
`scheduled` is the registered strobe `visit_q` -- "a visit is due" -- and
`visit_valid` is the output -- "and it is being presented". They differ exactly
when `valid` is low, which is the point of section 3.7 and the reason both are
recorded.

A new `H` line starts a new run, so the `---` separators are for the reader,
not the parser.

Usage:
    python3 gen_observer_hw_vectors.py
"""

import os
import sys

from observer_hw import simulate

VECTOR_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "..", "sim", "vectors")

BANNER = (
    "# Observer hardware vectors -- generated by gen_observer_hw_vectors.py\n"
    "# from validation/observer_hw.py. Do not edit by hand.\n"
    "#\n"
    "# H <N> <oneshot> <cycles>\n"
    "# C <rst> <start> <trigger> <valid> <state> <running> <column>"
    " <scheduled> <visit_valid> <done> <aborted>\n"
)


def schedules():
    """
    The runs, as (name, N, start_cycle, triggers, valid_low, rsts, oneshot,
    cycles).

    Chosen to exercise the section 3.11 table rather than to look impressive: a
    plain pass, a pass at maximum rate, one-shot endings at every small N, the
    N = 1 degenerate case, N = 0 refused at the door, and invalidations
    including one that lands exactly on a visit.
    """
    runs = []

    # A plain pass, sparse against a clock that is mostly idle.
    for N in (1, 2, 3, 4, 5, 8, 16, 17, 64):
        trigs = tuple(range(2, 2 + 3 * N, 3))
        end = (max(trigs) if trigs else 0) + 3
        runs.append((f"n{N}_sparse", N, 0, trigs, (), (), False,
                     max(N + 4, end)))

    # The same, at one visit per clock -- the rate the whole design claims.
    for N in (1, 2, 3, 4, 8, 64):
        runs.append((f"n{N}_full_rate", N, 0, tuple(range(1, 3 * N)),
                     (), (), False, 3 * N + 3))

    # One-shot: the pass must end, and no further trigger may produce a visit.
    for N in (1, 2, 3, 8):
        runs.append((f"n{N}_oneshot", N, 0, tuple(range(1, 4 * N)),
                     (), (), True, 4 * N + 3))

    # N = 0 is not an instance, so a start is refused and nothing runs.
    runs.append(("n0_refused", 0, 0, tuple(range(1, 8)), (), (), False, 10))

    # Invalidations: during a pass, on the very cycle a visit is due, and
    # during the pass that follows a restart.
    runs.append(("inv_midway", 8, 0, tuple(range(1, 30)), set(range(9, 15)),
                 (), False, 30))
    runs.append(("inv_on_visit", 8, 0, tuple(range(1, 30)), set(range(1, 6)),
                 (), False, 30))
    runs.append(("inv_then_restart", 8, 0, tuple(range(12, 40)),
                 set(range(6, 10)), (), False, 40))

    # A reset in the middle of a pass: reset is not an abort.
    runs.append(("rst_midway", 8, 0, tuple(range(1, 30)), (), (10,), False, 20))

    return runs


def emit(fh, name, N, start_cycle, triggers, valid_low, rsts, oneshot, cycles):
    """Write one run: a header, then a line per cycle."""
    trigs = set(triggers)
    lows = set(valid_low)
    rst_set = set(rsts)
    result = simulate(N, start_cycle=start_cycle, trigger_cycles=triggers,
                      valid_low=valid_low, oneshot=oneshot, cycles=cycles,
                      rst_cycles=rsts)

    fh.write(f"# {name}\n")
    fh.write(f"H {N} {int(oneshot)} {cycles}\n")
    for c, cyc in enumerate(result.cycles):
        start = 1 if start_cycle == c else 0
        trig = 1 if c in trigs else 0
        valid = 0 if c in lows else 1
        rst = 1 if c in rst_set else 0
        fh.write(
            f"C {rst} {start} {trig} {valid} {int(cyc.running)} "
            f"{int(cyc.running)} {cyc.column} {int(cyc.scheduled)} "
            f"{int(cyc.visit_valid)} {int(cyc.done)} {int(cyc.aborted)}\n"
        )
    fh.write("---\n")
    return result


def main():
    if not os.path.isdir(VECTOR_DIR):
        print(f"FAIL  no such directory: {VECTOR_DIR}")
        return 1

    path = os.path.join(VECTOR_DIR, "obshw_edge.txt")
    runs = schedules()
    total_visits = total_suppressed = total_aborts = 0
    n_runs = 0

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(BANNER)
        for run in runs:
            name, N, start, trigs, lows, rsts, oneshot, cycles = run
            r = emit(fh, name, N, start, trigs, lows, rsts, oneshot, cycles)
            total_visits += len(r.visits)
            total_suppressed += r.suppressed
            total_aborts += r.aborts
            n_runs += 1

    # The corpus has to be worth replaying: a set of runs that never
    # invalidates, never aborts and never suppresses a visit would also pass
    # against a much worse engine than this one.
    problems = []
    if total_suppressed < 1:
        problems.append("no run suppresses a visit")
    if total_aborts < 1:
        problems.append("no run aborts")
    if not any(N == 1 for (_, N, *_r) in runs):
        problems.append("no N = 1 run")
    if not any(N == 0 for (_, N, *_r) in runs):
        problems.append("no N = 0 run")
    if problems:
        for p in problems:
            print(f"FAIL  {p}")
        return 1

    print(f"obshw_edge.txt: {n_runs} runs, {total_visits} visits, "
          f"{total_suppressed} suppressed, {total_aborts} aborts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
