"""
Observer peripheral bus corpus: requested cycles, and what the contract says.

The generator for `sim/vectors/obswb_*.txt`, the files replayed against
`rtl/bcmc_obs_wb.v`. Every expected value comes from
`validation/observer_periph.py`, which implements `docs/Observer_Register_Map.md`
and is held to it.

The format
----------
One run is a header and then one line per clock cycle, inputs and expectations
together, so a replay harness never computes anything:

    H <name> <N> <C> <cycles>
    C <valid> <rst> <cyc> <stb> <we> <adr> <sel> <dat> \
      <ack> <err> <rdata> <running> <visit_valid> <column> <done> <aborted> \
      <column_bits>

Every field is hexadecimal. A transaction occupies two cycles: the request, then
an idle cycle in which the response appears. That is not padding -- the slave
qualifies a new access with `!ack && !err`, so a master that held `stb` through
the response cycle would have its next request ignored. The corpus drives the
bus the way a correct master does.

The observable interface, and only that
---------------------------------------
`running`, `visit_valid`, `column`, `done` and `aborted` are declared module
outputs. The corpus records those and the bus response, and NOTHING internal:
not the engine's cursor, not `visit_q`/`scheduled`, not the model's latches
except where a register read makes them observable. The Python model may inspect
more than this -- it is the oracle -- and that asymmetry is deliberate.

Why the corpus cannot be weakened by accident
---------------------------------------------
`CATEGORIES` names the cases that can distinguish a worse implementation, and
`build()` constructs the corpus *from that list*: each category is a function
that must contribute at least one transaction, and generation fails if one does
not. A later edit that quietly drops the invalidation case, or the refusal case,
breaks generation rather than silently shipping a weaker corpus.

Usage:
    python3 gen_observer_wb_vectors.py
"""

import os
import sys

from observer_periph import (
    CTRL_ONESHOT, CTRL_RESET, CTRL_START, CTRL_STEP,
    OBS_CAPS, OBS_CTRL, OBS_ID, OBS_PASS, OBS_STATUS, OBS_TRIG, OBS_VERSION,
    ObserverPeriph, replay,
)

VECTOR_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "..", "sim", "vectors")

BANNER = (
    "# Observer peripheral bus corpus -- generated by gen_observer_wb_vectors.py\n"
    "# from validation/observer_periph.py. Do not edit by hand.\n"
    "#\n"
    "# H <name> <N> <C> <cycles>\n"
    "# C <valid> <rst> <cyc> <stb> <we> <adr> <sel> <dat> <ack> <err> <rdata>"
    " <running> <visit_valid> <column> <done> <aborted> <column_bits>\n"
)

# The matrix used by the projection runs: N = 2, C = 2, both weights 1 at
# offset 0, so (0 + c) mod 2 < 1 holds only for c = 0 -- row i is active in
# column 0 and not in column 1. Those words come from the mathematics.
N2, C2 = 2, 2
W2 = [1, 1]
O2 = [0, 0]


def expected_bits(N, W, O, column, C):
    """
    M(:, column) as a bit vector, from reference.py -- the golden matrix, in the
    same sense observers.py and the engine corpus use it. The projection is a
    module output, not a register, so this is the only way the corpus can carry
    it.
    """
    from reference import bcmc_column
    if N < 1 or C < 1 or column >= N:
        return 0
    v = 0
    for i, b in enumerate(bcmc_column(W, O, column, N)[:C]):
        if b:
            v |= (1 << i)
    return v


def observable(p, N, W, O, C):
    """The declared outputs, and nothing internal."""
    c = p.eng.outputs(p.valid)
    return (int(c.running), int(c.visit_valid), c.column, int(c.done),
            int(c.aborted), expected_bits(N, W, O, c.column, C))


def walk(name, N, C, W, O, ops):
    """Run one peripheral through `ops`; return the run's cycle records."""
    p = ObserverPeriph(N=N, C=C, max_c=16)
    rows = []
    txns = 0

    def emit(cyc, stb, we, adr, sel, dat, resp, outs):
        rows.append((int(p.valid), 0, cyc, stb, we, adr, sel, dat,
                     resp[0], resp[1], resp[2],
                     outs[0], outs[1], outs[2], outs[3], outs[4], outs[5]))

    def response_cycle(acked, rdata):
        outs = observable(p, p.N, W, O, C)
        emit(0, 0, 0, 0, 0xF, 0, (int(acked), int(not acked), rdata), outs)
        p.tick()

    for op in ops:
        kind = op[0]
        if kind == 'v':
            p.valid = bool(op[1])
        elif kind == 'i':
            emit(0, 0, 0, 0, 0xF, 0, (0, 0, 0), observable(p, p.N, W, O, C))
            p.tick()
        elif kind == 'w':
            _, adr, dat, sel = op
            outs = observable(p, p.N, W, O, C)
            acked = p.write(adr, dat, sel=sel)
            emit(1, 1, 1, adr, sel, dat, (0, 0, 0), outs)
            p.tick()
            response_cycle(acked, 0)
            txns += 1
        elif kind == 'r':
            _, adr, sel = op
            outs = observable(p, p.N, W, O, C)
            acked, data = p.read(adr, sel=sel)
            emit(1, 1, 0, adr, sel, 0, (0, 0, 0), outs)
            p.tick()
            response_cycle(acked, data)
            txns += 1
        elif kind == 'h':
            # The request is HELD through the response cycle. The slave
            # qualifies acceptance with !ack && !err, so it must not answer a
            # second time; a third, idle cycle catches it if it did.
            _, adr, dat, sel = op
            outs = observable(p, p.N, W, O, C)
            acked = p.write(adr, dat, sel=sel)
            emit(1, 1, 1, adr, sel, dat, (0, 0, 0), outs)
            p.tick()
            outs2 = observable(p, p.N, W, O, C)
            emit(1, 1, 1, adr, sel, dat, (int(acked), int(not acked), 0), outs2)
            p.tick()
            # A third, IDLE cycle: the master has withdrawn the request
            # (cyc & stb low), so the slave answers neither the held request nor
            # anything else. ack and err are BOTH low. Do not use
            # response_cycle() here: its err is !acked, so passing acked = 0
            # would record an error response, which is itself a second answer
            # -- contradicting the point of the cycle, and violating the
            # contract, which answers only qualified requests.
            emit(0, 0, 0, 0, 0xF, 0, (0, 0, 0), observable(p, p.N, W, O, C))
            p.tick()
            txns += 1
        else:
            raise ValueError(f"unknown op {op!r}")

    return {"name": name, "N": N, "C": C, "rows": rows, "txns": txns}


def w(adr, dat, sel=0xF):
    return ('w', adr, dat, sel)


def r(adr, sel=0xF):
    return ('r', adr, sel)


def i():
    return ('i',)


def v(x):
    return ('v', x)


def h(adr, dat, sel=0xF):
    return ('h', adr, dat, sel)


# ---------------------------------------------------------------------------
# The categories. build() constructs the corpus FROM this table, so a category
# that stops contributing a transaction fails generation.
# ---------------------------------------------------------------------------

def categories():
    c = {}
    C1 = CTRL_ONESHOT

    c["identity_and_geometry"] = (2, 2, W2, O2, [
        r(OBS_ID), r(OBS_VERSION), r(OBS_CAPS), r(OBS_TRIG),
    ])
    c["every_mapped_register"] = (2, 2, W2, O2, [
        r(OBS_ID), r(OBS_VERSION), r(OBS_CAPS), r(OBS_CTRL), r(OBS_STATUS),
        r(OBS_PASS), r(OBS_TRIG),
    ])
    c["unmapped_classes"] = (2, 2, W2, O2, [
        r(0x01C), r(0x040), r(0x3FC), w(0x01C, 0), w(0x400, 0),
    ])
    c["refusals"] = (2, 2, W2, O2, [
        w(OBS_ID, 0), w(OBS_VERSION, 0), w(OBS_CAPS, 0), w(OBS_PASS, 0),
        w(OBS_TRIG, 0), w(OBS_CTRL, CTRL_START, sel=0x1),
    ])
    c["n_zero_refuses_start"] = (0, 2, W2, O2, [
        w(OBS_CTRL, C1 | CTRL_START), r(OBS_STATUS), r(OBS_PASS),
    ])
    c["deferred_write"] = (2, 2, W2, O2, [
        w(OBS_CTRL, C1), r(OBS_CTRL), i(), r(OBS_STATUS),
    ])
    c["oneshot_completion"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, C1 | CTRL_START), w(OBS_CTRL, C1 | CTRL_STEP),
        r(OBS_STATUS), r(OBS_PASS), r(OBS_CTRL),
    ])
    c["invalidation"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, C1 | CTRL_START), v(0), i(), i(), r(OBS_STATUS),
        v(1), r(OBS_STATUS),
    ])
    c["continuous_reset_restart"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, CTRL_START), r(OBS_STATUS),
        w(OBS_CTRL, CTRL_RESET), r(OBS_STATUS), r(OBS_PASS),
        w(OBS_CTRL, CTRL_START), r(OBS_STATUS),
    ])
    c["collision_stb_held"] = (2, 2, W2, O2, [
        v(1), h(OBS_CTRL, C1 | CTRL_START), r(OBS_STATUS),
    ])
    c["oneshot_step"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, C1 | CTRL_START), w(OBS_CTRL, C1 | CTRL_STEP),
        r(OBS_STATUS),
    ])
    c["oneshot_start_refused_half_apply"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, C1 | CTRL_START), w(OBS_CTRL, CTRL_START),
        r(OBS_CTRL), r(OBS_STATUS),
    ])
    c["nonzero_projection"] = (2, 2, W2, O2, [
        v(1), w(OBS_CTRL, C1 | CTRL_START), w(OBS_CTRL, C1 | CTRL_STEP),
        r(OBS_PASS),
    ])
    return c


def build():
    """Construct the corpus from the category table, and report any that is
    empty. Constructing from the table is the first protection."""
    runs = []
    missing = []
    for name, (N, C, W, O, ops) in categories().items():
        run = walk(name, N, C, W, O, ops)
        if run["txns"] < 1:
            missing.append(name)
        runs.append(run)
    return runs, missing


def main():
    if not os.path.isdir(VECTOR_DIR):
        print(f"FAIL  no such directory: {VECTOR_DIR}")
        return 1

    runs, missing = build()
    if missing:
        for m in missing:
            print(f"FAIL  category '{m}' contributed no transaction")
        return 1

    path = os.path.join(VECTOR_DIR, "obswb_edge.txt")
    total = 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(BANNER)
        for run in runs:
            fh.write(f"# {run['name']}\n")
            fh.write(f"H {run['name']} {run['N']} {run['C']} "
                     f"{len(run['rows'])}\n")
            for row in run["rows"]:
                fh.write("C " + " ".join(f"{f:x}" for f in row) + "\n")
            fh.write("---\n")
            total += len(run["rows"])

    # The second, independent protection: read the names back OUT of the file
    # and require every category to be there. build() having done its job is a
    # claim; this is the check.
    present = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# "):
                present.add(line[2:].strip())
    absent = sorted(n for n in categories() if n not in present)
    if absent:
        for a in absent:
            print(f"FAIL  '{a}' is not in the generated file")
        return 1

    print(f"obswb_edge.txt: {len(runs)} runs, {total} cycles, "
          f"{len(categories())} mandatory categories all present")
    return 0


if __name__ == "__main__":
    sys.exit(main())

