"""
Generate RTL test vectors from the executable specification.

Python produces the vectors; Verilog and C++ only ever read them. No expected
value is ever written by hand, and no testbench invents an answer.

    Proof  ->  reference.py  ->  vectors  ->  Verilator / Icarus  ->  RTL

File format
-----------
Deliberately trivial, so that both a C++ `ifstream` and Verilog `$fscanf` can
read it, and so that a human can read it too.

    # comments and blank lines are ignored

    N 8
    C 3

    6
    3
    5

    ---

    0
    6
    1

An `N` line begins a new case, so no case separator is needed and `C = 0`
requires no special handling. Within a case: `C` weights, then `---`, then `C`
offsets.

Usage
-----
    python3 validation/gen_vectors.py            # standard suites
    python3 validation/gen_vectors.py --big      # also the 10,000-case suite
"""

import argparse
import os
import random
import sys

import reference as ref

HERE = os.path.dirname(os.path.abspath(__file__))
VECTOR_DIR = os.path.normpath(os.path.join(HERE, "..", "sim", "vectors"))

SEED = 20260731


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------

def write_suite(path, title, cases):
    """
    Write a list of (weights, N) cases. Offsets come from reference.py, never
    from anything in this file.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w") as f:
        f.write(f"# {title}\n")
        f.write("#\n")
        f.write("# Generated by validation/gen_vectors.py from validation/reference.py\n")
        f.write(f"# Seed: {SEED}.  Do not edit by hand.\n")
        f.write("#\n")
        f.write("# Format:  N <n> / C <c> / <c weights> / --- / <c offsets>\n")

        for weights, N in cases:
            offsets = ref.bcmc_core(weights, N)
            assert len(offsets) == len(weights)

            f.write("\n")
            f.write(f"N {N}\n")
            f.write(f"C {len(weights)}\n")
            f.write("\n")
            for w in weights:
                f.write(f"{w}\n")
            f.write("\n---\n\n")
            for o in offsets:
                f.write(f"{o}\n")

    total_rows = sum(len(w) for w, _ in cases)
    size = os.path.getsize(path)
    print(
        f"  {os.path.basename(path):24s} "
        f"{len(cases):7,d} cases  {total_rows:9,d} rows  {size/1024:8.1f} KiB"
    )


# ---------------------------------------------------------------------------
# Suites
# ---------------------------------------------------------------------------

def cases_edge():
    """
    Hand-chosen cases: the boundaries of the specification, plus the three
    examples that appear in the documentation.
    """
    return [
        # Degenerate shapes
        ([], 1),                                        # C = 0, N = 1
        ([], 5),                                        # C = 0
        ([], 65535),                                    # C = 0, N maximal
        ([0], 1),                                       # single zero weight
        ([0, 0, 0], 7),                                 # W = 0
        ([0] * 16, 16),                                 # all zero

        # N = 1: every offset must be 0
        ([1], 1),
        ([1, 1, 1, 1], 1),
        ([0, 1, 0, 1], 1),

        # Saturated weights, w_i = N: the boundary of Lemma 2's hypothesis
        ([5], 5),
        ([5, 5], 5),
        ([5, 5, 5, 5, 5], 5),
        ([10, 10], 10),

        # Wrapping and zeros interleaved
        ([0, 4, 0, 4], 4),
        ([10, 0, 0, 10], 10),
        ([4, 2, 0, 4, 3], 5),
        ([1, 1, 1, 1, 1], 5),
        ([7, 1], 8),                                    # exact wrap to 0
        ([8], 8),                                       # single full row
        ([1] * 8, 8),                                   # offsets walk 0..7

        # The documented examples
        ([6, 3, 5], 8),
        ([4, 13, 13, 11, 12, 5, 10, 2, 0, 12], 15),
        ([24, 26, 28, 11, 8, 20, 19, 26, 2, 30], 31),

        # Powers of two and a prime, to exercise the comparator/subtractor
        ([3, 3, 3, 3, 3], 4),
        ([2, 3, 5, 7, 11, 13], 17),
        ([16] * 4, 16),
    ]


def cases_random(count, max_N, max_C, rng):
    """Uniform random cases within the specification."""
    cases = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        C = rng.randint(0, max_C)
        cases.append(([rng.randint(0, N) for _ in range(C)], N))
    return cases


def cases_biased(count, max_N, max_C, rng):
    """
    Random cases biased toward the interesting boundaries: weights of 0 and N,
    which drive the wrap logic hardest.
    """
    cases = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        C = rng.randint(1, max_C)
        weights = []
        for _ in range(C):
            roll = rng.random()
            if roll < 0.30:
                weights.append(0)
            elif roll < 0.60:
                weights.append(N)
            elif roll < 0.75:
                weights.append(max(0, N - 1))
            else:
                weights.append(rng.randint(0, N))
        cases.append((weights, N))
    return cases


def cases_large(rng):
    """Wide N and long C, to exercise the full 16-bit datapath."""
    shapes = [
        (65535, 64),
        (65535, 256),
        (10000, 200),
        (4096, 1024),
        (1024, 1024),
        (2, 512),          # narrowest non-trivial N, long stream
        (3, 300),
    ]
    return [
        ([rng.randint(0, N) for _ in range(C)], N)
        for N, C in shapes
    ]


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--big",
        action="store_true",
        help="also generate core_random_10k.txt (large, not committed)",
    )
    parser.add_argument(
        "--out",
        default=VECTOR_DIR,
        help="output directory (default: sim/vectors)",
    )
    args = parser.parse_args()

    rng = random.Random(SEED)

    print(f"Writing vectors to {args.out}")
    print()

    write_suite(
        os.path.join(args.out, "core_edge.txt"),
        "BCMC Core edge cases",
        cases_edge(),
    )

    write_suite(
        os.path.join(args.out, "core_random.txt"),
        "BCMC Core random cases (N<=64, C<=64)",
        cases_random(500, max_N=64, max_C=64, rng=rng),
    )

    write_suite(
        os.path.join(args.out, "core_biased.txt"),
        "BCMC Core random cases biased toward w=0 and w=N",
        cases_biased(500, max_N=64, max_C=64, rng=rng),
    )

    write_suite(
        os.path.join(args.out, "core_large.txt"),
        "BCMC Core large cases (N up to 65,535, C up to 1,024)",
        cases_large(rng),
    )

    if args.big:
        write_suite(
            os.path.join(args.out, "core_random_10k.txt"),
            "BCMC Core random cases, 10,000 vectors (N<=64, C<=64)",
            cases_random(10_000, max_N=64, max_C=64, rng=rng),
        )

    print()
    print("Done. Offsets were produced by validation/reference.py.")
    if not args.big:
        print("Run with --big for the 10,000-case regression suite.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
