"""
Generate RTL test vectors from the executable specification.

Python produces the vectors; Verilog and C++ only ever read them. No expected
value is ever written by hand, and no testbench invents an answer.

    Proof  ->  reference.py  ->  vectors  ->  Verilator / Icarus  ->  RTL

File formats
------------
Deliberately trivial, so that both a C++ `ifstream` and Verilog `$fscanf` can
read them, and so that a human can read them too. In both formats `#` begins a
comment to end of line and blank lines are insignificant.

**Core format** (`core_*.txt`) -- one streamed transform per case:

    N 8
    C 3

    6
    3
    5

    ---

    0
    6
    1

An `N` line begins a new case, so no case separator is needed and `C = 0`
requires no special handling. Within a case: `C` weights, then `---`, then `C`
offsets.

**Cell format** (`cell_*.txt`) -- one evaluation per line, because an
exhaustive sweep runs to hundreds of thousands of cases and the keyword form
would be absurd:

    #    N  weight  offset  column  bit
         8       6       0       3    1

**Matrix format** (`matrix_*.txt`) -- one whole matrix per case, for the two
projections `bcmc_row` and `bcmc_column`:

    N 8 C 3
    W 6 3 5
    O 0 6 1
    R 11111100
    R 11000001
    R 01111100
    L 3 2 2 2 2 2 1 1

`R` rows are written column 0 first. `L` is the column occupancy vector, the
quantity the Balance Theorem constrains.

Usage
-----
    python3 validation/gen_vectors.py            # standard suites
    python3 validation/gen_vectors.py --big      # also the soak suites
"""

import argparse
import itertools
import os
import random
import sys

import reference as ref

HERE = os.path.dirname(os.path.abspath(__file__))
VECTOR_DIR = os.path.normpath(os.path.join(HERE, "..", "sim", "vectors"))

SEED = 20260731


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------

def write_suite(path, title, cases):
    """
    Write a list of (weights, N) cases. Offsets come from reference.py, never
    from anything in this file.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w") as f:
        f.write(f"# {title}\n")
        f.write("#\n")
        f.write("# Generated by validation/gen_vectors.py from validation/reference.py\n")
        f.write(f"# Seed: {SEED}.  Do not edit by hand.\n")
        f.write("#\n")
        f.write("# Format:  N <n> / C <c> / <c weights> / --- / <c offsets>\n")

        for weights, N in cases:
            offsets = ref.bcmc_core(weights, N)
            assert len(offsets) == len(weights)

            f.write("\n")
            f.write(f"N {N}\n")
            f.write(f"C {len(weights)}\n")
            f.write("\n")
            for w in weights:
                f.write(f"{w}\n")
            f.write("\n---\n\n")
            for o in offsets:
                f.write(f"{o}\n")

    total_rows = sum(len(w) for w, _ in cases)
    size = os.path.getsize(path)
    print(
        f"  {os.path.basename(path):24s} "
        f"{len(cases):7,d} cases  {total_rows:9,d} rows  {size/1024:8.1f} KiB"
    )


def write_cell_suite(path, title, tuples):
    """
    Write a list of (N, weight, offset, column) tuples. The expected bit comes
    from reference.py's bcmc_cell(), never from anything in this file.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w") as f:
        f.write(f"# {title}\n")
        f.write("#\n")
        f.write("# Generated by validation/gen_vectors.py from validation/reference.py\n")
        f.write(f"# Seed: {SEED}.  Do not edit by hand.\n")
        f.write("#\n")
        f.write("# One evaluation of the BCMC characteristic function per line:\n")
        f.write("#\n")
        f.write("#     bit = 1  iff  ((column - offset) mod N) < weight\n")
        f.write("#\n")
        f.write("#      N  weight  offset  column  bit\n")

        for N, weight, offset, column in tuples:
            bit = ref.bcmc_cell(weight, offset, column, N)
            f.write(f"{N:7d} {weight:7d} {offset:7d} {column:7d} {bit:4d}\n")

    size = os.path.getsize(path)
    print(
        f"  {os.path.basename(path):24s} "
        f"{len(tuples):7,d} cases  {'':9s}       {size/1024:8.1f} KiB"
    )


def write_matrix_suite(path, title, cases):
    """
    Write a list of (N, weights) cases as whole matrices.

    Everything after the weights -- the offsets, every bit of the matrix, the
    column occupancies -- comes from reference.py. Nothing in this file computes
    a matrix bit.

    One case, in tokens:

        N <N> C <C>
        W <weights, C numbers>
        O <offsets, C numbers>
        R <bit string for row 0>      (C of these; char 0 is column 0)
        L <occupancies, N numbers>

    The row bit strings are written column 0 first, matching the bit ordering
    of rtl/bcmc_row.v (row_bits[0] is column 0). L(j) is the popcount of
    column j: the quantity the Balance Theorem constrains.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    total_bits = 0

    with open(path, "w") as f:
        f.write(f"# {title}\n")
        f.write("#\n")
        f.write("# Generated by validation/gen_vectors.py from validation/reference.py\n")
        f.write(f"# Seed: {SEED}.  Do not edit by hand.\n")
        f.write("#\n")
        f.write("# One whole matrix per case:\n")
        f.write("#\n")
        f.write("#     N <N> C <C>\n")
        f.write("#     W <weights>          C numbers\n")
        f.write("#     O <offsets>          C numbers, from bcmc_core\n")
        f.write("#     R <bits>             one per row; character 0 is column 0\n")
        f.write("#     L <occupancies>      N numbers; L(j) = popcount of column j\n")
        f.write("#\n")

        for N, weights in cases:
            C = len(weights)
            offsets = ref.bcmc_core(weights, N)
            matrix = ref.bcmc_matrix(weights, N)
            occupancy = ref.column_occupancy(weights, N)

            f.write("\n")
            f.write(f"N {N} C {C}\n")
            f.write("W " + " ".join(str(w) for w in weights) + "\n")
            f.write("O " + " ".join(str(o) for o in offsets) + "\n")
            for row in matrix:
                f.write("R " + "".join(str(b) for b in row) + "\n")
            f.write("L " + " ".join(str(x) for x in occupancy) + "\n")

            total_bits += C * N

    size = os.path.getsize(path)
    print(
        f"  {os.path.basename(path):24s} "
        f"{len(cases):7,d} cases  {total_bits:9,d} bits  {size/1024:8.1f} KiB"
    )


# ---------------------------------------------------------------------------
# Core suites
# ---------------------------------------------------------------------------

def cases_edge():
    """
    Hand-chosen cases: the boundaries of the specification, plus the three
    examples that appear in the documentation.
    """
    return [
        # Degenerate shapes
        ([], 1),                                        # C = 0, N = 1
        ([], 5),                                        # C = 0
        ([], 65535),                                    # C = 0, N maximal
        ([0], 1),                                       # single zero weight
        ([0, 0, 0], 7),                                 # W = 0
        ([0] * 16, 16),                                 # all zero

        # N = 1: every offset must be 0
        ([1], 1),
        ([1, 1, 1, 1], 1),
        ([0, 1, 0, 1], 1),

        # Saturated weights, w_i = N: the boundary of Lemma 2's hypothesis
        ([5], 5),
        ([5, 5], 5),
        ([5, 5, 5, 5, 5], 5),
        ([10, 10], 10),

        # Wrapping and zeros interleaved
        ([0, 4, 0, 4], 4),
        ([10, 0, 0, 10], 10),
        ([4, 2, 0, 4, 3], 5),
        ([1, 1, 1, 1, 1], 5),
        ([7, 1], 8),                                    # exact wrap to 0
        ([8], 8),                                       # single full row
        ([1] * 8, 8),                                   # offsets walk 0..7

        # The documented examples
        ([6, 3, 5], 8),
        ([4, 13, 13, 11, 12, 5, 10, 2, 0, 12], 15),
        ([24, 26, 28, 11, 8, 20, 19, 26, 2, 30], 31),

        # Powers of two and a prime, to exercise the comparator/subtractor
        ([3, 3, 3, 3, 3], 4),
        ([2, 3, 5, 7, 11, 13], 17),
        ([16] * 4, 16),
    ]


def cases_random(count, max_N, max_C, rng):
    """Uniform random cases within the specification."""
    cases = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        C = rng.randint(0, max_C)
        cases.append(([rng.randint(0, N) for _ in range(C)], N))
    return cases


def cases_biased(count, max_N, max_C, rng):
    """
    Random cases biased toward the interesting boundaries: weights of 0 and N,
    which drive the wrap logic hardest.
    """
    cases = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        C = rng.randint(1, max_C)
        weights = []
        for _ in range(C):
            roll = rng.random()
            if roll < 0.30:
                weights.append(0)
            elif roll < 0.60:
                weights.append(N)
            elif roll < 0.75:
                weights.append(max(0, N - 1))
            else:
                weights.append(rng.randint(0, N))
        cases.append((weights, N))
    return cases


def cases_large(rng):
    """Wide N and long C, to exercise the full 16-bit datapath."""
    shapes = [
        (65535, 64),
        (65535, 256),
        (10000, 200),
        (4096, 1024),
        (1024, 1024),
        (2, 512),          # narrowest non-trivial N, long stream
        (3, 300),
    ]
    return [
        ([rng.randint(0, N) for _ in range(C)], N)
        for N, C in shapes
    ]


# ---------------------------------------------------------------------------
# Cell suites
#
# The cell's input space is finite and small. For modest N we do not sample it,
# we enumerate it: every legal (N, weight, offset, column) tuple. There is no
# stronger statement available about any module in this project.
# ---------------------------------------------------------------------------

def cells_exhaustive(max_N):
    """
    Every legal tuple for 1 <= N <= max_N:

        0 <= weight <= N        (Lemma 2's hypothesis, inclusive)
        0 <= offset <  N        (offsets are residues)
        0 <= column <  N        (column indices are residues)

    That is sum over N of (N+1)*N*N tuples: 6,734 for max_N = 12.
    """
    return [
        (N, weight, offset, column)
        for N in range(1, max_N + 1)
        for weight in range(0, N + 1)
        for offset in range(0, N)
        for column in range(0, N)
    ]


def cells_edge():
    """
    Hand-chosen *inputs* -- never answers -- at the boundaries of the
    characteristic function. The wrap boundary is the interesting one:
    `column == offset` is the first marked column, and `column == offset - 1`
    is the last, reached only by wrapping the whole way round.
    """
    tuples = []

    # N = 1: the only residue is 0; weight 0 gives 0, weight 1 gives 1.
    tuples += [(1, 0, 0, 0), (1, 1, 0, 0)]

    for N in (2, 3, 8, 16, 255, 256, 4096, 65535):
        last = N - 1
        for offset in (0, 1, last // 2, last):
            for weight in (0, 1, N - 1, N):
                if not (0 <= weight <= N):
                    continue
                tuples += [
                    (N, weight, offset, offset),                # first marked
                    (N, weight, offset, (offset + 1) % N),
                    (N, weight, offset, (offset - 1) % N),      # last marked
                    (N, weight, offset, 0),                     # column 0
                    (N, weight, offset, last),                  # column N-1
                    (N, weight, offset, (offset + weight) % N),  # first unmarked
                ]

    # Deduplicate while preserving order, so the file stays readable.
    seen = set()
    unique = []
    for t in tuples:
        if t not in seen:
            seen.add(t)
            unique.append(t)
    return unique


def cells_random(count, max_N, rng):
    """
    Uniform random tuples with N up to 65,535, covering the wide datapath that
    exhaustive enumeration cannot reach.
    """
    tuples = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        # Bias weight toward the boundaries, as for the Core.
        roll = rng.random()
        if roll < 0.15:
            weight = 0
        elif roll < 0.30:
            weight = N
        elif roll < 0.40:
            weight = N - 1
        else:
            weight = rng.randint(0, N)
        offset = rng.randint(0, N - 1)
        column = rng.randint(0, N - 1)
        tuples.append((N, weight, offset, column))
    return tuples


# ---------------------------------------------------------------------------
# Matrix suites
#
# These drive rtl/bcmc_row.v and rtl/bcmc_column.v, the two projections of the
# characteristic function, and with them the matrix-level statements: row
# conservation and the Balance Theorem. Both modules are sized at elaboration,
# so the suites stay within MAX_N = MAX_C = 32.
# ---------------------------------------------------------------------------

MATRIX_MAX = 32


def matrices_edge():
    """The boundaries of the specification, as whole matrices."""
    return [
        (1, []),                       # no rows at all
        (5, []),                       # no rows, wider N
        (1, [0]),                      # one row, empty
        (1, [1]),                      # one row, full
        (1, [1, 0, 1]),                # N = 1: every offset is 0
        (7, [0, 0, 0]),                # W = 0: an all-zero matrix
        (5, [5, 5, 5]),                # w = N: an all-one matrix
        (4, [0, 4, 0, 4]),             # empty and full interleaved
        (8, [1] * 8),                  # the diagonal
        (8, [7, 1]),                   # exact wrap to 0
        (5, [4, 2, 0, 4, 3]),
        (8, [6, 3, 5]),                # the documented example
        (15, [4, 13, 13, 11, 12, 5, 10, 2, 0, 12]),
        (31, [24, 26, 28, 11, 8, 20, 19, 26, 2, 30]),
        (MATRIX_MAX, [MATRIX_MAX] * MATRIX_MAX),      # the widest full matrix
        (MATRIX_MAX, [0] * MATRIX_MAX),               # the widest empty matrix
        (MATRIX_MAX, list(range(MATRIX_MAX + 1))[:MATRIX_MAX]),
    ]


def matrices_exhaustive(max_N, max_C):
    """
    EVERY weight vector for 1 <= N <= max_N and 0 <= C <= max_C, so every
    matrix of that shape is assembled by the RTL and checked bit for bit.
    """
    cases = []
    for N in range(1, max_N + 1):
        for C in range(0, max_C + 1):
            for combo in itertools.product(range(0, N + 1), repeat=C):
                cases.append((N, list(combo)))
    return cases


def matrices_random(count, max_N, max_C, rng):
    """Random matrices, weights biased toward 0 and N."""
    cases = []
    for _ in range(count):
        N = rng.randint(1, max_N)
        C = rng.randint(0, max_C)
        weights = []
        for _ in range(C):
            roll = rng.random()
            if roll < 0.20:
                weights.append(0)
            elif roll < 0.40:
                weights.append(N)
            else:
                weights.append(rng.randint(0, N))
        cases.append((N, weights))
    return cases


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--big",
        action="store_true",
        help="also generate the soak suites (large, not committed)",
    )
    parser.add_argument(
        "--out",
        default=VECTOR_DIR,
        help="output directory (default: sim/vectors)",
    )
    args = parser.parse_args()

    rng = random.Random(SEED)

    print(f"Writing vectors to {args.out}")
    print()

    write_suite(
        os.path.join(args.out, "core_edge.txt"),
        "BCMC Core edge cases",
        cases_edge(),
    )

    write_suite(
        os.path.join(args.out, "core_random.txt"),
        "BCMC Core random cases (N<=64, C<=64)",
        cases_random(500, max_N=64, max_C=64, rng=rng),
    )

    write_suite(
        os.path.join(args.out, "core_biased.txt"),
        "BCMC Core random cases biased toward w=0 and w=N",
        cases_biased(500, max_N=64, max_C=64, rng=rng),
    )

    write_suite(
        os.path.join(args.out, "core_large.txt"),
        "BCMC Core large cases (N up to 65,535, C up to 1,024)",
        cases_large(rng),
    )

    if args.big:
        write_suite(
            os.path.join(args.out, "core_random_10k.txt"),
            "BCMC Core random cases, 10,000 vectors (N<=64, C<=64)",
            cases_random(10_000, max_N=64, max_C=64, rng=rng),
        )

    print()

    write_cell_suite(
        os.path.join(args.out, "cell_edge.txt"),
        "BCMC Cell edge cases (wrap boundaries, extremal weights)",
        cells_edge(),
    )

    write_cell_suite(
        os.path.join(args.out, "cell_exhaustive.txt"),
        "BCMC Cell: EVERY legal tuple for N <= 12",
        cells_exhaustive(12),
    )

    write_cell_suite(
        os.path.join(args.out, "cell_random.txt"),
        "BCMC Cell random cases (N up to 65,535)",
        cells_random(5_000, max_N=65535, rng=rng),
    )

    if args.big:
        write_cell_suite(
            os.path.join(args.out, "cell_exhaustive_32.txt"),
            "BCMC Cell: EVERY legal tuple for N <= 32",
            cells_exhaustive(32),
        )

    print()

    write_matrix_suite(
        os.path.join(args.out, "matrix_edge.txt"),
        "BCMC Matrix edge cases (whole matrices, N and C <= 32)",
        matrices_edge(),
    )

    write_matrix_suite(
        os.path.join(args.out, "matrix_exhaustive.txt"),
        "BCMC Matrix: EVERY weight vector for N <= 4, C <= 4",
        matrices_exhaustive(4, 4),
    )

    write_matrix_suite(
        os.path.join(args.out, "matrix_random.txt"),
        f"BCMC Matrix random cases (N and C <= {MATRIX_MAX})",
        matrices_random(300, max_N=MATRIX_MAX, max_C=MATRIX_MAX, rng=rng),
    )

    if args.big:
        write_matrix_suite(
            os.path.join(args.out, "matrix_exhaustive_6.txt"),
            "BCMC Matrix: EVERY weight vector for N <= 6, C <= 5",
            matrices_exhaustive(6, 5),
        )
        write_matrix_suite(
            os.path.join(args.out, "matrix_random_5k.txt"),
            f"BCMC Matrix random cases, 5,000 matrices (N and C <= {MATRIX_MAX})",
            matrices_random(5_000, max_N=MATRIX_MAX, max_C=MATRIX_MAX, rng=rng),
        )

    print()
    print("Done. Every expected value was produced by validation/reference.py.")
    if not args.big:
        print("Run with --big for the soak suites.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
