"""
Emit the observer vectors that sw/bcmc_observer.c must reproduce.

`pi` is a pure function of its declared inputs -- N for the sequential
observer, (N, seed) for the permuted one -- so unlike a bus conversation it
needs no recording apparatus at all. It can simply be tabulated, and then the C
implementation can be checked against it index for index.

That is the whole reason docs/Observers.md pins the generator, the bounded draw
and the loop direction. "A Fisher-Yates shuffle" is not a specification; two
implementations of it disagree unless the random source is written down. These
files are what turn the written-down version into something a C compiler can be
held to.

WHY THIS FILE IS NOT PART OF gen_vectors.py

Everything gen_vectors.py writes is an instance of the BCMC mathematics, and is
read by two independent simulators. Nothing here is either. An observer is not
part of the BCMC definition, and no Verilog reads these files, because
traversal is software -- the register map deliberately has no "next column"
register. They are kept separate so that neither fact gets blurred.

Run:
    python3 validation/gen_observer_vectors.py
"""

import os

from observers import MASK32, SplitMix32, permuted_order, sequential_order

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sim", "vectors")

# Seeds worth pinning: the boundaries, the generator's own constant (which
# makes state == 0 after the first add, the one state a weaker generator would
# stick on), and a handful of ordinary values.
SEEDS = [0, 1, 2, 3, 7, 42, 12345, 0x9E3779B9, 0x61C88647, 0xDEADBEEF, 0xFFFFFFFF]

# N sweeps every small value, because the shuffle's loop bounds are where an
# off-by-one lives, then a few larger ones so that a multi-word draw mask and a
# multi-word column both occur.
LENGTHS = list(range(1, 33)) + [40, 63, 64, 65, 100, 128, 255, 256]

# How many outputs of the generator to tabulate per seed. Enough that a wrong
# constant cannot hide, few enough that the file stays readable.
PRNG_DRAWS = 16


def write_prng(path):
    """
    G <seed> <next() 16 times>, all hexadecimal.

    The generator is checked before the shuffle that uses it, for the same
    reason reference.py is checked before the RTL that implements it: if the
    two disagree here, every permutation below is meaningless, and a failure
    should say which of the two things is wrong.
    """
    lines = [
        "# Observer PRNG vectors -- docs/Observers.md, 'The random source'.",
        "#",
        "# G <seed> <z0> .. <z%d>   all hexadecimal, all 32-bit." % (PRNG_DRAWS - 1),
        "#",
        "# Generated by validation/gen_observer_vectors.py. Do not edit.",
        "",
    ]

    for seed in SEEDS:
        rng = SplitMix32(seed)
        draws = " ".join("%08X" % rng.next() for _ in range(PRNG_DRAWS))
        lines.append("G %08X %s" % (seed, draws))

    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return len(SEEDS)


def write_orders(path):
    """
    S <N> <pi(0)> .. <pi(N-1)>            the sequential observer
    P <N> <seed> <pi(0)> .. <pi(N-1)>     the permuted observer

    The sequential rows are tabulated rather than assumed. `pi(t) = t` is
    obvious, which is exactly the kind of claim that gets implemented wrongly
    and never checked, and it costs one line per N to make it checkable.
    """
    lines = [
        "# Observer traversal vectors -- docs/Observers.md, reference observers 1 and 2.",
        "#",
        "# S <N> <pi(0)> .. <pi(N-1)>          pi(t) = t",
        "# P <N> <seed> <pi(0)> .. <pi(N-1)>   seeded Fisher-Yates, seed hexadecimal",
        "#",
        "# Every row is a bijection of 0 .. N-1: that is O1, and it is the whole",
        "# structural content of the observer contract.",
        "#",
        "# Generated by validation/gen_observer_vectors.py. Do not edit.",
        "",
    ]

    rows = 0
    for n in LENGTHS:
        lines.append("S %d %s" % (n, " ".join(str(t) for t in sequential_order(n))))
        rows += 1
        for seed in SEEDS:
            p = permuted_order(n, seed)
            assert sorted(p) == list(range(n)), "the generator emitted a non-bijection"
            lines.append("P %d %08X %s" % (n, seed, " ".join(str(t) for t in p)))
            rows += 1

    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return rows


def main():
    out = os.path.normpath(OUT_DIR)
    os.makedirs(out, exist_ok=True)

    prng_path = os.path.join(out, "observer_prng.txt")
    order_path = os.path.join(out, "observer_order.txt")

    n_prng = write_prng(prng_path)
    n_order = write_orders(order_path)

    assert all(0 <= s <= MASK32 for s in SEEDS), "a seed left 32 bits"

    print("observer_prng.txt   %3d seeds x %d draws" % (n_prng, PRNG_DRAWS))
    print("observer_order.txt  %3d traversals over %d lengths" % (n_order, len(LENGTHS)))
    print("pi is now a table sw/bcmc_observer.c can be held to.")


if __name__ == "__main__":
    main()
