"""
Conformance tests for the BCMC peripheral model.

`bcmc_periph.py` is to `docs/Register_Map.md` what `reference.py` is to
`docs/BCMC.md`: an executable restatement of a specification. This script is
what makes that restatement trustworthy, and it follows the same three rules the
project has used since v0.2.

  1. **No invented answers.** Every matrix bit an expectation contains comes
     from `sim/vectors/matrix_*.txt`, generated by `reference.py`. The same
     files drive `sim/bcmc_row_test.cpp`, `sim/tb_column.v` and this suite, so
     agreement between them is agreement about one object, not three.

  2. **Only the register map.** The matrices compared here are built by writing
     and reading registers, exactly as `sw/bcmc.c` will. Nothing reaches inside
     the peripheral to fetch a value the bus does not expose.

  3. **The error model is re-derived, not shared.** `expected_errors()` below is
     an independent transcription of the E1-E4 table in the specification. It
     shares no code with `BcmcPeripheral._check_access`, so the two disagreeing
     is a real finding.

Run:
    python3 validation/test_periph.py
"""

import os
import random
import sys

import reference as ref
from bcmc_periph import (
    COLUMN_BASE,
    COLUMN_LIMIT,
    CTRL_IRQ_EN,
    CTRL_START,
    ID_VALUE,
    OFFSET_BASE,
    REG_C,
    REG_CAPS,
    REG_CELL,
    REG_CELL_COL,
    REG_CELL_ROW,
    REG_CTRL,
    REG_ID,
    REG_N,
    REG_STATUS,
    REG_VERSION,
    REGION_SIZE,
    STATUS_BUSY,
    STATUS_IRQ,
    STATUS_VALID,
    VERSION_VALUE,
    WEIGHT_BASE,
    WINDOW_SPAN,
    BcmcPeripheral,
    BusError,
    PreconditionError,
    program,
    read_column,
    read_matrix,
    read_offsets,
)

VECTOR_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sim", "vectors")

SEL_WORD = 0xF


# ---------------------------------------------------------------------------
# The reference vectors
# ---------------------------------------------------------------------------

def load_matrix_vectors(path):
    """
    Parse one sim/vectors/matrix_*.txt file.

    The format is the one gen_vectors.py writes and sim/common/vectors.cpp
    reads:

        N <N> C <C>
        W <C weights>
        O <C offsets>
        R <bitstring>        one line per row; character 0 is column 0
        L <N occupancies>
    """
    cases = []
    cur = None
    with open(path) as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            tok = line.split()
            tag = tok[0]
            if tag == "N":
                if len(tok) != 4 or tok[2] != "C":
                    raise ValueError(f"{path}:{lineno}: malformed header")
                cur = {"N": int(tok[1]), "C": int(tok[3]), "rows": []}
            elif cur is None:
                raise ValueError(f"{path}:{lineno}: '{tag}' outside a case")
            elif tag == "W":
                cur["weights"] = [int(t) for t in tok[1:]]
            elif tag == "O":
                cur["offsets"] = [int(t) for t in tok[1:]]
            elif tag == "R":
                cur["rows"].append([int(ch) for ch in tok[1]])
            elif tag == "L":
                cur["loads"] = [int(t) for t in tok[1:]]
                validate_case(cur, f"{path}:{lineno}")
                cases.append(cur)
                cur = None
            else:
                raise ValueError(f"{path}:{lineno}: unknown tag '{tag}'")
    if cur is not None:
        raise ValueError(f"{path}: last case has no L line")
    return cases


def validate_case(case, where):
    """The vector file must be internally well formed before it is believed."""
    N, C = case["N"], case["C"]
    if len(case["weights"]) != C or len(case["offsets"]) != C:
        raise ValueError(f"{where}: W/O length != C")
    if len(case["rows"]) != C:
        raise ValueError(f"{where}: {len(case['rows'])} R lines != C = {C}")
    if len(case["loads"]) != N:
        raise ValueError(f"{where}: L length != N")
    for row in case["rows"]:
        if len(row) != N:
            raise ValueError(f"{where}: row length != N")


# ---------------------------------------------------------------------------
# One case, through the register map alone
# ---------------------------------------------------------------------------

def check_vector_case(case, max_c, by_cell):
    """Return a list of failure messages (empty if the case passes)."""
    fails = []
    N, C = case["N"], case["C"]
    weights, expect_rows = case["weights"], case["rows"]

    dev = BcmcPeripheral(max_c=max_c)
    program(dev, N, weights)

    status = dev.read(REG_STATUS)
    if status & STATUS_BUSY:
        fails.append("BUSY still set after the polling loop returned")
    if not status & STATUS_VALID:
        fails.append("VALID not set after a completed transform")

    # --- the canonical representation, read back over the bus ---------------
    if read_offsets(dev, C) != case["offsets"]:
        fails.append("OFFSET window != the offsets in the vector file")

    for i in range(C):
        if dev.read(WEIGHT_BASE + 4 * i) != weights[i]:
            fails.append(f"WEIGHT[{i}] does not read back what was written")
            break

    # --- the matrix, through the COLUMN projection --------------------------
    rows = read_matrix(dev, N, C)
    if rows != expect_rows:
        fails.append("COLUMN projection != the matrix in the vector file")

    # --- the matrix, through CELL_ROW / CELL_COL / CELL ---------------------
    if by_cell and read_matrix(dev, N, C, by_cell=True) != expect_rows:
        fails.append("CELL projection != the matrix in the vector file")

    # --- the proved properties, re-established from bus reads only ----------
    for i in range(C):
        if sum(rows[i]) != weights[i]:
            fails.append(f"row conservation: row {i} popcount {sum(rows[i])} != {weights[i]}")
            break

    loads = [sum(rows[i][j] for i in range(C)) for j in range(N)]
    if loads != case["loads"]:
        fails.append("column occupancy != the L line in the vector file")

    W = sum(weights)
    q, r = divmod(W, N) if N else (0, 0)
    if loads != [q + 1] * r + [q] * (N - r):
        fails.append(f"Balance Theorem: W = {W} = {q}*{N} + {r} not honoured")

    # --- rows that do not exist are inactive lanes, not stale data ----------
    if C < max_c:
        dev.write(REG_CELL_ROW, C)
        for j in range(N):
            dev.write(REG_CELL_COL, j)
            if dev.read(REG_CELL) & 1:
                fails.append(f"row {C} >= C reads 1 at column {j}")
                break
        if dev.read(OFFSET_BASE + 4 * C) != 0:
            fails.append(f"OFFSET[{C}] was not cleared by the transform")

    return fails


# ---------------------------------------------------------------------------
# The error model, transcribed independently from docs/Register_Map.md
# ---------------------------------------------------------------------------

RO_REGS = (REG_ID, REG_VERSION, REG_CAPS, REG_CELL)
RW_REGS = (REG_CTRL, REG_STATUS, REG_N, REG_C, REG_CELL_ROW, REG_CELL_COL)


def expected_errors(dev, addr, write, sel=SEL_WORD, data=0):
    """
    Every reason the specification gives for refusing this access.

    A set, not a single reason, because the specification fixes *that* an
    access errs, not which condition is reported when several hold at once.
    Precedence is an implementation's business; refusal is the contract.
    """
    reasons = set()

    if addr < 0 or addr >= REGION_SIZE or addr % 4 != 0:
        reasons.add("E1")
        return reasons | ({"E3"} if sel != SEL_WORD else set())

    if sel != SEL_WORD:
        reasons.add("E3")

    in_weight = WEIGHT_BASE <= addr < WEIGHT_BASE + WINDOW_SPAN
    in_offset = OFFSET_BASE <= addr < OFFSET_BASE + WINDOW_SPAN
    in_column = COLUMN_BASE <= addr < COLUMN_LIMIT

    if addr in RO_REGS or addr in RW_REGS:
        if write and addr in RO_REGS:
            reasons.add("E2")
    elif in_column:
        if (addr - COLUMN_BASE) // 4 >= dev.column_words:
            reasons.add("E1")
        elif write:
            reasons.add("E2")
    elif in_weight:
        if (addr - WEIGHT_BASE) // 4 >= dev.max_c:
            reasons.add("E1")
    elif in_offset:
        if (addr - OFFSET_BASE) // 4 >= dev.max_c:
            reasons.add("E1")
        elif write:
            reasons.add("E2")
    else:
        reasons.add("E1")

    matrix_read = not write and (addr == REG_CELL or in_column or in_offset)
    context_write = write and (addr in (REG_N, REG_C) or in_weight)
    start_write = write and addr == REG_CTRL and bool(data & CTRL_START)

    # The two E4 rows overlap. Because START clears VALID before raising BUSY,
    # `BUSY` implies `!VALID`, so a matrix read while BUSY is refused twice
    # over and no bus master can tell which rule did it. The specification
    # states both anyway -- one is about a context being rewritten, the other
    # about a matrix not existing -- but a test cannot separate them, and this
    # comment is here so that nobody later mistakes that for a missing test.
    if dev.busy and (matrix_read or context_write or start_write):
        reasons.add("E4")
    if not dev.valid and matrix_read:
        reasons.add("E4")

    return reasons


def snapshot(dev):
    """Everything a write could legitimately change, and nothing else."""
    return (
        list(dev.weights), list(dev.offsets),
        dev.n, dev.c, dev.cell_row, dev.cell_col,
        dev.busy, dev.valid, dev.irq, dev.irq_en,
    )


def make_device(state, max_c=64):
    """A peripheral in one of the three states the E4 table distinguishes."""
    if state == "fresh":
        return BcmcPeripheral(max_c=max_c)
    if state == "valid":
        dev = BcmcPeripheral(max_c=max_c)
        program(dev, 8, [6, 3, 5])
        return dev
    if state == "busy":
        dev = BcmcPeripheral(max_c=max_c, latency=1_000_000)
        program(dev, 8, [6, 3, 5], poll=False)
        return dev
    raise ValueError(state)


def probe(dev, addr, write, sel=SEL_WORD, data=0):
    """Perform one access; return the reason it erred, or None."""
    try:
        if write:
            dev.write(addr, data, sel)
        else:
            dev.read(addr, sel)
    except BusError as exc:
        return exc.reason
    return None


# ---------------------------------------------------------------------------
# Suites
# ---------------------------------------------------------------------------

def suite_identity():
    ok = True
    dev = BcmcPeripheral()
    if dev.read(REG_ID) != ID_VALUE:
        print("  FAIL [identity]: ID is not 'BCMC'")
        ok = False
    if dev.read(REG_VERSION) != VERSION_VALUE:
        print("  FAIL [identity]: VERSION is not 0x00000400")
        ok = False

    for max_c, val_w, idx_w in [(64, 16, 16), (1, 8, 8), (256, 32, 32), (33, 12, 20)]:
        dev = BcmcPeripheral(max_c=max_c, val_w=val_w, idx_w=idx_w)
        caps = dev.read(REG_CAPS)
        got = (caps >> 24, (caps >> 16) & 0xFF, caps & 0xFFFF)
        if got != (idx_w, val_w, max_c):
            print(f"  FAIL [identity]: CAPS 0x{caps:08X} decodes as {got}")
            ok = False

    # ID, VERSION and CAPS are readable in every state, including BUSY.
    for state in ("fresh", "valid", "busy"):
        dev = make_device(state)
        for addr in (REG_ID, REG_VERSION, REG_CAPS, REG_STATUS, REG_CTRL):
            if probe(dev, addr, write=False) is not None:
                print(f"  FAIL [identity]: 0x{addr:03X} unreadable while {state}")
                ok = False
    if ok:
        print("  ID, VERSION and CAPS agree with the parameters in every state.")
    return ok


def suite_vectors(files):
    ok = True
    total = 0
    for name, max_c, by_cell_every in files:
        path = os.path.join(VECTOR_DIR, name)
        cases = load_matrix_vectors(path)
        for n, case in enumerate(cases):
            if case["C"] > max_c:
                continue
            fails = check_vector_case(case, max_c, by_cell=(n % by_cell_every == 0))
            total += 1
            if fails:
                ok = False
                print(f"  FAIL [{name} case {n}]  N={case['N']} weights={case['weights']}")
                for f in fails:
                    print(f"        {f}")
                return False
        print(f"  {len(cases):,} cases from {name} (MAX_C = {max_c}) passed.")
    if ok:
        print(f"  {total:,} matrices built entirely out of register transactions.")
    return ok


def suite_error_model():
    """
    Every aligned address in the 4 KiB region, read and written, in all three
    states -- plus unaligned and out-of-region addresses, and partial selects.
    """
    ok = True
    probed = 0

    addresses = list(range(0, REGION_SIZE, 4))
    addresses += [0x001, 0x002, 0x003, 0x005, 0x401, 0x803, REGION_SIZE, REGION_SIZE + 4]

    for state in ("fresh", "valid", "busy"):
        dev = make_device(state)
        for addr in addresses:                       # reads never mutate state
            want = expected_errors(dev, addr, write=False)
            got = probe(dev, addr, write=False)
            probed += 1
            if want and got not in want:
                print(f"  FAIL [{state} read 0x{addr:03X}]: got {got}, expected one of {want}")
                ok = False
            if not want and got is not None:
                print(f"  FAIL [{state} read 0x{addr:03X}]: refused with {got}")
                ok = False

        for addr in addresses:
            want = expected_errors(dev, addr, write=True)
            before = snapshot(dev)
            got = probe(dev, addr, write=True)
            probed += 1
            if want and got not in want:
                print(f"  FAIL [{state} write 0x{addr:03X}]: got {got}, expected one of {want}")
                ok = False
            if want and snapshot(dev) != before:
                print(f"  FAIL [{state} write 0x{addr:03X}]: erring write had a side effect")
                ok = False
            if not want:
                if got is not None:
                    print(f"  FAIL [{state} write 0x{addr:03X}]: refused with {got}")
                    ok = False
                dev = make_device(state)             # a legal write moved us
        if not ok:
            return False

    # Partial selects are refused everywhere, read or write.
    for state in ("fresh", "valid", "busy"):
        for sel in (0x0, 0x1, 0x3, 0x7, 0xE):
            dev = make_device(state)
            for addr in (REG_ID, REG_N, REG_CTRL, WEIGHT_BASE, OFFSET_BASE, COLUMN_BASE):
                for write in (False, True):
                    want = expected_errors(dev, addr, write, sel=sel)
                    got = probe(dev, addr, write, sel=sel)
                    probed += 1
                    if got not in want:
                        print(f"  FAIL [sel 0x{sel:X} at 0x{addr:03X}]: got {got}, want {want}")
                        ok = False
    if not ok:
        return False

    # START while BUSY is E4, and the whole write must be discarded: IRQ_EN
    # may not be left enabled by a refused CTRL write.
    dev = make_device("busy")
    before = snapshot(dev)
    got = probe(dev, REG_CTRL, write=True, data=CTRL_START | CTRL_IRQ_EN)
    probed += 1
    if got != "E4":
        print(f"  FAIL [START while BUSY]: got {got}, expected E4")
        ok = False
    if snapshot(dev) != before or dev.irq_en:
        print("  FAIL [START while BUSY]: the refused write changed IRQ_EN")
        ok = False

    # Writing CTRL with START clear is legal at any time, BUSY or not.
    if probe(dev, REG_CTRL, write=True, data=CTRL_IRQ_EN) is not None:
        print("  FAIL [CTRL while BUSY]: refused a write that does not start anything")
        ok = False

    if ok:
        print(f"  {probed:,} accesses classified exactly as the specification requires.")
    return ok


def suite_state():
    ok = True

    # Nothing is readable about a matrix that does not exist yet.
    dev = BcmcPeripheral()
    if dev.read(REG_STATUS) != 0:
        print("  FAIL [state]: STATUS is not 0 after reset")
        ok = False
    for addr in (REG_CELL, COLUMN_BASE, OFFSET_BASE):
        if probe(dev, addr, write=False) != "E4":
            print(f"  FAIL [state]: 0x{addr:03X} answered while VALID = 0")
            ok = False

    program(dev, 8, [6, 3, 5])
    if not dev.read(REG_STATUS) & STATUS_VALID:
        print("  FAIL [state]: VALID not set after a transform")
        ok = False

    # Every write that changes the context invalidates the matrix; the two
    # query-index registers do not, because an index is not the context.
    for addr, data in [(REG_N, 8), (REG_C, 3), (WEIGHT_BASE, 6)]:
        program(dev, 8, [6, 3, 5])
        dev.write(addr, data)
        if dev.read(REG_STATUS) & STATUS_VALID:
            print(f"  FAIL [state]: writing 0x{addr:03X} left VALID set")
            ok = False
        if probe(dev, REG_CELL, write=False) != "E4":
            print(f"  FAIL [state]: CELL answered after writing 0x{addr:03X}")
            ok = False

    program(dev, 8, [6, 3, 5])
    dev.write(REG_CELL_ROW, 1)
    dev.write(REG_CELL_COL, 7)
    if not dev.read(REG_STATUS) & STATUS_VALID:
        print("  FAIL [state]: a query index write cleared VALID")
        ok = False
    if dev.read(REG_CELL) & 1 != 1:
        print("  FAIL [state]: M(1,7) != 1 for the documented example")
        ok = False

    # BUSY and VALID are never true together. This is load bearing: it is what
    # makes "no matrix exists" the single reason a matrix read is refused,
    # whether the context is mid-transform or was merely never transformed.
    dev = BcmcPeripheral(latency=3)
    program(dev, 8, [6, 3, 5], poll=False)
    seen = []
    while True:
        status = dev.read(REG_STATUS)
        seen.append(status)
        if status & STATUS_BUSY and status & STATUS_VALID:
            print("  FAIL [state]: BUSY and VALID both set")
            ok = False
        if not status & STATUS_BUSY:
            break
    if len(seen) != 4:
        print(f"  FAIL [state]: latency 3 observed as {len(seen) - 1} busy polls")
        ok = False

    # The interrupt: level-sensitive, gated by IRQ_EN, cleared by writing 1.
    dev = BcmcPeripheral()
    program(dev, 8, [6, 3, 5])
    if not dev.read(REG_STATUS) & STATUS_IRQ:
        print("  FAIL [irq]: completion did not set IRQ")
        ok = False
    if dev.irq_out:
        print("  FAIL [irq]: pin asserted with IRQ_EN clear")
        ok = False
    dev.write(REG_CTRL, CTRL_IRQ_EN)
    if not dev.irq_out:
        print("  FAIL [irq]: pin not asserted with IRQ pending and IRQ_EN set")
        ok = False
    if dev.read(REG_CTRL) != CTRL_IRQ_EN:
        print("  FAIL [irq]: CTRL does not read back IRQ_EN, or START reads 1")
        ok = False
    dev.write(REG_STATUS, 0)
    if not dev.read(REG_STATUS) & STATUS_IRQ:
        print("  FAIL [irq]: writing 0 cleared IRQ")
        ok = False
    dev.write(REG_STATUS, STATUS_IRQ)
    if dev.read(REG_STATUS) & STATUS_IRQ or dev.irq_out:
        print("  FAIL [irq]: write-1-to-clear did not clear IRQ")
        ok = False
    if not dev.read(REG_STATUS) & STATUS_VALID:
        print("  FAIL [irq]: acknowledging the interrupt disturbed VALID")
        ok = False

    # Reset returns every visible bit to its documented value.
    dev.reset()
    if dev.read(REG_STATUS) != 0 or dev.read(REG_N) != 0 or dev.read(REG_C) != 0:
        print("  FAIL [state]: reset did not clear STATUS, N and C")
        ok = False
    if dev.read(REG_CTRL) != 0 or any(dev.read(WEIGHT_BASE + 4 * i) for i in range(dev.max_c)):
        print("  FAIL [state]: reset did not clear CTRL and the WEIGHT window")
        ok = False

    if ok:
        print("  BUSY, VALID and IRQ behave as the state section describes.")
    return ok


def suite_inactive_lanes():
    """
    Rows above C must depend on C alone. This is the corner that a naive
    implementation gets wrong: shrink C and the weights of the rows that just
    vanished are still sitting in the window.
    """
    ok = True
    dev = BcmcPeripheral(max_c=64)

    program(dev, 8, [6, 3, 5, 7, 2])
    program(dev, 8, [6, 3, 5])              # C shrinks; WEIGHT[3..4] go stale

    if dev.read(WEIGHT_BASE + 4 * 3) != 7:
        print("  FAIL [lanes]: the test's premise is wrong, WEIGHT[3] is not stale")
        ok = False

    expect = ref.bcmc_matrix([6, 3, 5], 8)
    if read_matrix(dev, 8, 3) != expect:
        print("  FAIL [lanes]: the matrix changed when C shrank")
        ok = False

    for row in range(3, 6):
        dev.write(REG_CELL_ROW, row)
        for j in range(8):
            dev.write(REG_CELL_COL, j)
            if dev.read(REG_CELL) & 1:
                print(f"  FAIL [lanes]: stale row {row} reads 1 at column {j}")
                ok = False
        if dev.read(OFFSET_BASE + 4 * row) != 0:
            print(f"  FAIL [lanes]: OFFSET[{row}] was not cleared")
            ok = False

    for j in range(8):
        dev.write(REG_CELL_COL, j)
        for k in range(dev.column_words):
            word = dev.read(COLUMN_BASE + 4 * k)
            high = word >> 3 if k == 0 else word
            if high:
                print(f"  FAIL [lanes]: COLUMN[{k}] has bits above C set")
                ok = False

    # C = 0 is legal, and produces a matrix with no rows at all.
    dev = BcmcPeripheral()
    program(dev, 5, [])
    if read_matrix(dev, 5, 0) != [] or read_offsets(dev, 0) != []:
        print("  FAIL [lanes]: C = 0 did not produce an empty matrix")
        ok = False
    for j in range(5):
        dev.write(REG_CELL_COL, j)
        if dev.read(COLUMN_BASE) != 0 or dev.read(REG_CELL) & 1:
            print(f"  FAIL [lanes]: C = 0 reports occupancy at column {j}")
            ok = False

    if ok:
        print("  rows at or above C answer 0, whatever is left in the window.")
    return ok


def suite_order_and_gaps():
    """
    Values do not depend on when accesses happen, only on their order -- and
    steps 3 to 5 of the programming sequence have no order among themselves.
    This is gap invariance, stated at the bus rather than at the Core.
    """
    ok = True
    N, weights = 12, [7, 0, 12, 5, 9]
    expect = ref.bcmc_matrix(weights, N)

    def build(dev, order, gap):
        for step in order:
            for _ in range(gap):
                dev.read(REG_STATUS)             # idle traffic, no side effects
            if step == "N":
                dev.write(REG_N, N)
            elif step == "C":
                dev.write(REG_C, len(weights))
            else:
                for i, w in enumerate(weights):
                    dev.write(WEIGHT_BASE + 4 * i, w)
        dev.write(REG_CTRL, CTRL_START)
        while not dev.read(REG_STATUS) & STATUS_VALID:
            pass                                 # VALID, not !BUSY: step 7
        return read_matrix(dev, N, len(weights))

    orders = [
        ("N", "C", "W"), ("C", "N", "W"), ("W", "N", "C"),
        ("W", "C", "N"), ("N", "W", "C"), ("C", "W", "N"),
    ]
    for order in orders:
        for gap in (0, 1, 5):
            for latency in (0, 2, 7):
                dev = BcmcPeripheral(latency=latency)
                if build(dev, order, gap) != expect:
                    print(f"  FAIL [order]: {order} gap={gap} latency={latency}")
                    ok = False

    # Re-programming the same peripheral leaves no trace of the previous run.
    dev = BcmcPeripheral()
    for weights2, n2 in [([1, 2, 3], 4), ([0], 1), ([31] * 8, 31), ([6, 3, 5], 8)]:
        program(dev, n2, weights2)
        if read_matrix(dev, n2, len(weights2)) != ref.bcmc_matrix(weights2, n2):
            print(f"  FAIL [order]: reuse with N={n2} weights={weights2}")
            ok = False

    if ok:
        print(f"  {len(orders)} programming orders x 3 gaps x 3 latencies agree.")
    return ok


def suite_preconditions():
    """
    Mathematical preconditions are not the bus's business. The model refuses
    them as `reference.py` does -- but never as a BusError, because that would
    claim the register map checks the mathematics, and it does not.
    """
    ok = True
    for N, weights in [(5, [6]), (5, [7, 3]), (0, [0]), (4, [1, 5])]:
        dev = BcmcPeripheral()
        dev.write(REG_N, N)
        dev.write(REG_C, len(weights))
        for i, w in enumerate(weights):
            dev.write(WEIGHT_BASE + 4 * i, w)
        try:
            dev.write(REG_CTRL, CTRL_START)
        except PreconditionError:
            continue
        except BusError as exc:
            print(f"  FAIL [precondition]: N={N} w={weights} reported as {exc.reason}")
            ok = False
            continue
        print(f"  FAIL [precondition]: N={N} w={weights} silently accepted")
        ok = False

    # C > MAX_C is geometry, not mathematics, so it is refused at the bus.
    dev = BcmcPeripheral(max_c=8)
    if probe(dev, WEIGHT_BASE + 4 * 8, write=True) != "E1":
        print("  FAIL [precondition]: WEIGHT[MAX_C] was not refused with E1")
        ok = False
    if ok:
        print("  preconditions are refused as mathematics, never as bus errors.")
    return ok


def suite_random_programs(num, max_n, max_c_used, max_c):
    """
    Random programs, compared against reference.py rather than a vector file,
    so the suite is not limited to N and C <= 32.
    """
    ok = True
    dev = BcmcPeripheral(max_c=max_c)
    for _ in range(num):
        N = random.randint(1, max_n)
        C = random.randint(0, max_c_used)
        weights = [random.randint(0, N) for _ in range(C)]
        program(dev, N, weights)
        if read_offsets(dev, C) != ref.bcmc_core(weights, N):
            print(f"  FAIL [random]: offsets differ for N={N} weights={weights}")
            return False
        j = random.randrange(N)
        if read_column(dev, j, C) != ref.bcmc_column(weights, ref.bcmc_core(weights, N), j, N):
            print(f"  FAIL [random]: column {j} differs for N={N} weights={weights}")
            return False
        if C:
            i = random.randrange(C)
            dev.write(REG_CELL_ROW, i)
            dev.write(REG_CELL_COL, j)
            offsets = ref.bcmc_core(weights, N)
            if dev.read(REG_CELL) & 1 != ref.bcmc_cell(weights[i], offsets[i], j, N):
                print(f"  FAIL [random]: M({i},{j}) differs for N={N} weights={weights}")
                return False
    if ok:
        print(f"  {num:,} random programs (N<={max_n}, C<={max_c_used}) agree with reference.py.")
    return ok


# ---------------------------------------------------------------------------

def main():
    random.seed(20260731)
    results = []

    print("Identification:")
    results.append(suite_identity())
    print()

    print("The error model:")
    results.append(suite_error_model())
    print()

    print("State, interrupts and reset:")
    results.append(suite_state())
    print()

    print("Inactive lanes:")
    results.append(suite_inactive_lanes())
    print()

    print("Order and gap invariance:")
    results.append(suite_order_and_gaps())
    print()

    print("Preconditions:")
    results.append(suite_preconditions())
    print()

    print("Reference matrices, built out of register transactions:")
    results.append(suite_vectors([
        ("matrix_edge.txt", 64, 1),
        ("matrix_edge.txt", 32, 1),
        ("matrix_random.txt", 64, 1),
        ("matrix_random.txt", 33, 4),
        ("matrix_exhaustive.txt", 64, 8),
    ]))
    print()

    print("Random programs:")
    results.append(suite_random_programs(300, max_n=64, max_c_used=64, max_c=64))
    print()

    if all(results):
        print("bcmc_periph.py satisfies docs/Register_Map.md.")
        print("The register map is now an executable contract for rtl/bcmc_wb.v.")
        return 0

    print("CONFORMANCE FAILED")
    return 1


if __name__ == "__main__":
    sys.exit(main())
